@extends('layouts.member')
@section('title', 'Portfolio Centre')
@section('content')
<div class="workspace-canvas"><div class="ohc-dashboard-container">
    <x-workspace-heading eyebrow="Protect and grow" title="Portfolio Centre" description="An educational portfolio workspace built from holdings you record. It is not connected to a brokerage.">
        <x-slot:actions><button class="workspace-button is-secondary" type="button" data-toggle-panel="new-portfolio">New portfolio</button>@if($portfolio)<button class="workspace-button" type="button" data-toggle-panel="new-holding">Add holding</button>@endif</x-slot:actions>
    </x-workspace-heading>
    <section class="workspace-card compact-form-panel" id="new-portfolio" hidden><form method="POST" action="{{ route('portfolio.store') }}" class="workspace-form-grid">@csrf<label>Portfolio name<input name="name" required placeholder="e.g. Core"></label><label>Benchmark symbol<input name="benchmark_symbol" value="SPY" required></label><label>Currency<input name="currency" value="USD" maxlength="3" required></label><div><button class="workspace-button">Create portfolio</button></div></form></section>
    @if(!$portfolio)
        <x-workspace-empty title="Build your first portfolio" copy="Create a portfolio, then enter your actual holdings and cost basis. OHC will calculate allocation and drift without inventing market prices."><x-slot:action><button class="workspace-button" type="button" data-toggle-panel="new-portfolio">Create portfolio</button></x-slot:action></x-workspace-empty>
    @else
        <nav class="portfolio-switcher">@foreach($portfolios as $item)<a class="{{ $item->id===$portfolio->id ? 'is-active' : '' }}" href="{{ route('portfolio.index',['portfolio'=>$item->id]) }}">{{ $item->name }}</a>@endforeach</nav>
        <section class="workspace-card compact-form-panel" id="new-holding" {{ $errors->any() ? '' : 'hidden' }}><div class="workspace-card__heading"><div><p>{{ $portfolio->name }}</p><h2>Add or update a holding</h2></div></div><form method="POST" action="{{ route('portfolio.holdings.store',$portfolio) }}" class="workspace-form-grid">@csrf<label>Symbol<input name="symbol" required placeholder="e.g. SPY"></label><label>Name<input name="name" placeholder="Optional security name"></label><label>Asset class<select name="asset_class"><option>Equity</option><option>Fixed Income</option><option>Cash</option><option>Commodity</option><option>Crypto</option><option>Alternative</option></select></label><label>Quantity<input type="number" step="any" min="0.00000001" name="quantity" required></label><label>Average cost<input type="number" step="any" min="0" name="average_cost" required></label><label>Target weight %<input type="number" step="0.01" min="0" max="100" name="target_weight"></label><div><button class="workspace-button">Save holding</button></div></form></section>
        <section class="workspace-stat-grid"><article><p>Recorded cost basis</p><strong>{{ $portfolio->currency }} {{ number_format($totalCost,2) }}</strong><span>Quantity × average cost</span></article><article><p>Holdings</p><strong>{{ $rows->count() }}</strong><span>Saved instruments</span></article><article><p>Asset classes</p><strong>{{ $allocation->count() }}</strong><span>Recorded allocation</span></article><article><p>Benchmark</p><strong>{{ $portfolio->benchmark_symbol }}</strong><span>Reference only</span></article></section>
        <div class="workspace-grid portfolio-grid"><section class="workspace-card"><div class="workspace-card__heading"><div><p>Allocation</p><h2>Cost-basis allocation</h2></div><span>Not live valuation</span></div>@if($allocation->isNotEmpty())<div class="allocation-bars">@foreach($allocation as $class=>$value)@php($percent=$totalCost>0?round($value/$totalCost*100,1):0)<div><header><strong>{{ $class }}</strong><span>{{ $percent }}%</span></header><i><b style="width:{{ $percent }}%"></b></i><small>{{ $portfolio->currency }} {{ number_format($value,2) }}</small></div>@endforeach</div>@else<p class="muted-copy">Add holdings to calculate allocation.</p>@endif</section>
            <section class="workspace-card portfolio-pricing-note"><p>Pricing status</p><h2>Licensed quote adapter not connected</h2><span>TradingView widgets can display market data, but they do not provide a licensed backend price feed for calculating your portfolio. To avoid misleading you, current value, performance and health score remain unavailable.</span><a href="{{ route('markets.index') }}">Open live Markets workspace</a></section></div>
        <section class="workspace-card"><div class="workspace-card__heading"><div><p>{{ $portfolio->name }}</p><h2>Holdings and target drift</h2></div></div><div class="workspace-table-wrap"><table class="workspace-table"><thead><tr><th>Holding</th><th>Class</th><th>Quantity</th><th>Average cost</th><th>Recorded weight</th><th>Target</th><th>Drift</th><th></th></tr></thead><tbody>@forelse($rows as $holding)<tr><td><strong>{{ $holding->symbol }}</strong><small>{{ $holding->name }}</small></td><td>{{ $holding->asset_class }}</td><td>{{ rtrim(rtrim($holding->quantity,'0'),'.') }}</td><td>{{ $portfolio->currency }} {{ number_format((float)$holding->average_cost,2) }}</td><td>{{ $holding->recorded_weight }}%</td><td>{{ $holding->target_weight !== null ? $holding->target_weight.'%' : '—' }}</td><td>{{ $holding->recorded_drift !== null ? ($holding->recorded_drift>0?'+':'').$holding->recorded_drift.'%' : '—' }}</td><td><form method="POST" action="{{ route('portfolio.holdings.destroy',[$portfolio,$holding]) }}" onsubmit="return confirm('Remove this holding?')">@csrf @method('DELETE')<button class="text-button is-danger">Remove</button></form></td></tr>@empty<tr><td colspan="8">No holdings recorded.</td></tr>@endforelse</tbody></table></div></section>
        <p class="workspace-disclaimer">Educational tracking only. OHC does not execute trades, custody assets, or provide personalised investment advice.</p>
    @endif
</div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('[data-toggle-panel]').forEach(function(button){button.addEventListener('click',function(){var panel=document.getElementById(button.dataset.togglePanel);panel.hidden=!panel.hidden;if(!panel.hidden)panel.scrollIntoView({behavior:'smooth'})})});</script>@endpush
