@extends('layouts.member')
@section('title', 'Trading Journal')
@section('content')
<div class="workspace-canvas"><div class="ohc-dashboard-container">
    <x-workspace-heading eyebrow="Review and improve" title="Trading Journal" description="Record every trade as structured data and review statistics calculated only from your own entries.">
        <x-slot:actions><button class="workspace-button" type="button" data-toggle-panel="trade-form">Log a trade</button></x-slot:actions>
    </x-workspace-heading>
    <section class="workspace-card journal-form" id="trade-form" {{ $errors->any() ? '' : 'hidden' }}><div class="workspace-card__heading"><div><p>New entry</p><h2>Log a trade</h2></div><button type="button" class="text-button" data-toggle-panel="trade-form">Close</button></div>
        <form method="POST" action="{{ route('journal.store') }}" enctype="multipart/form-data" class="workspace-form-grid">@csrf
            <label>Instrument<input name="instrument" value="{{ old('instrument') }}" required placeholder="e.g. NDX"></label><label>Direction<select name="direction" required><option value="long">Long</option><option value="short">Short</option></select></label><label>Trade time<input type="datetime-local" name="traded_at" value="{{ old('traded_at',now()->format('Y-m-d\TH:i')) }}" required></label><label>Outcome<select name="outcome"><option value="open">Open</option><option value="win">Win</option><option value="loss">Loss</option><option value="breakeven">Breakeven</option></select></label>
            <label>Entry price<input type="number" step="any" min="0" name="entry_price" value="{{ old('entry_price') }}"></label><label>Stop price<input type="number" step="any" min="0" name="stop_price" value="{{ old('stop_price') }}"></label><label>Target price<input type="number" step="any" min="0" name="target_price" value="{{ old('target_price') }}"></label><label>Risk %<input type="number" step="0.01" min="0" max="100" name="risk_percent" value="{{ old('risk_percent') }}"></label>
            <label>R multiple<input type="number" step="0.01" name="r_multiple" value="{{ old('r_multiple') }}"></label><label>Emotion<input name="emotion" value="{{ old('emotion') }}" placeholder="Calm, anxious, FOMO"></label><label>Confidence (1-5)<input type="number" min="1" max="5" name="confidence" value="{{ old('confidence') }}"></label><label>Screenshot<input type="file" name="screenshot" accept="image/*"></label>
            <label class="is-wide">Lessons learned<textarea name="lessons" rows="3">{{ old('lessons') }}</textarea></label><div class="is-wide"><button class="workspace-button" type="submit">Save trade</button></div>
        </form>
    </section>
    <section class="workspace-stat-grid"><article><p>Total trades</p><strong>{{ $stats['count'] }}</strong><span>Your recorded entries</span></article><article><p>Win rate</p><strong>{{ $stats['win_rate'] !== null ? $stats['win_rate'].'%' : 'Not enough data' }}</strong><span>Closed trades only</span></article><article><p>Average R</p><strong>{{ $stats['average_r'] !== null ? $stats['average_r'].'R' : 'Not recorded' }}</strong><span>Entries with an R value</span></article><article><p>Most traded</p><strong>{{ $stats['instrument'] ?: 'Not recorded' }}</strong><span>Based on your journal</span></article></section>
    <div class="workspace-grid journal-grid"><section class="workspace-card"><div class="workspace-card__heading"><div><p>Trade log</p><h2>Recent trades</h2></div><form method="GET" class="inline-filters"><input name="instrument" value="{{ request('instrument') }}" placeholder="Instrument"><select name="outcome"><option value="">All results</option>@foreach(['open','win','loss','breakeven'] as $result)<option value="{{ $result }}" @selected(request('outcome')===$result)>{{ ucfirst($result) }}</option>@endforeach</select><button>Filter</button></form></div>
        <div class="workspace-table-wrap"><table class="workspace-table"><thead><tr><th>Date</th><th>Instrument</th><th>Direction</th><th>Risk</th><th>R</th><th>Emotion</th><th>Result</th><th></th></tr></thead><tbody>@forelse($trades as $trade)<tr><td>{{ $trade->traded_at->format('j M, H:i') }}</td><td><strong>{{ $trade->instrument }}</strong></td><td>{{ ucfirst($trade->direction) }}</td><td>{{ $trade->risk_percent !== null ? $trade->risk_percent.'%' : '—' }}</td><td>{{ $trade->r_multiple !== null ? $trade->r_multiple.'R' : '—' }}</td><td>{{ $trade->emotion ?: '—' }}</td><td><span class="result-pill is-{{ $trade->outcome }}">{{ ucfirst($trade->outcome) }}</span></td><td><form method="POST" action="{{ route('journal.destroy',$trade) }}" onsubmit="return confirm('Remove this journal entry?')">@csrf @method('DELETE')<button class="text-button is-danger">Remove</button></form></td></tr>@empty<tr><td colspan="8">No trades match this view. Use “Log a trade” to create your first real journal entry.</td></tr>@endforelse</tbody></table></div>{{ $trades->links() }}</section>
        <aside class="workspace-card insight-card"><p>Journal analysis</p><h2>{{ $stats['count'] < 10 ? 'More data is needed' : 'Deterministic statistics active' }}</h2><span>@if($stats['count'] < 10) Record at least 10 trades before drawing behavioural conclusions. This prevents misleading claims from a small sample. @else Your headline statistics are calculated from your journal. AI analysis remains intentionally disabled for now. @endif</span><ul><li>Only your saved trades are counted.</li><li>Open trades do not affect win rate.</li><li>No recommendations are generated.</li></ul></aside></div>
</div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('[data-toggle-panel]').forEach(function(button){button.addEventListener('click',function(){var panel=document.getElementById(button.dataset.togglePanel);panel.hidden=!panel.hidden;if(!panel.hidden)panel.scrollIntoView({behavior:'smooth'})})});</script>@endpush
