@extends('layouts.admin')
@section('title','Settings') @section('heading','Platform and Billing Settings')
@section('content')
<div class="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Secret-safe configuration:</strong> Paystack secret and public keys remain in the environment file and are never shown or saved through this form.</div>
<form method="POST" action="{{ route('admin.settings.update') }}" class="grid gap-6 xl:grid-cols-2">@csrf @method('PATCH')
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Platform identity</h2><div class="mt-5 grid gap-4"><label class="grid gap-2"><span class="text-xs font-black">Platform name</span><input name="platform_name" value="{{ old('platform_name',$settings['platform_name'] ?? 'OHC Traderoom OS') }}" class="rounded-lg border-slate-300"></label><label class="grid gap-2"><span class="text-xs font-black">Support email</span><input type="email" name="support_email" value="{{ old('support_email',$settings['support_email'] ?? 'support@ohctraderoom.com') }}" class="rounded-lg border-slate-300"></label><label class="grid gap-2"><span class="text-xs font-black">Default billing currency</span><input name="default_currency" maxlength="3" value="{{ old('default_currency',$settings['default_currency'] ?? 'USD') }}" class="rounded-lg border-slate-300 uppercase"></label></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Paystack status</h2><div class="mt-5 space-y-3"><div class="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span class="font-bold">Server secret key</span><span class="rounded-full px-3 py-1 text-xs font-black {{ $paystackSecretConfigured?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800' }}">{{ $paystackSecretConfigured?'Configured':'Missing' }}</span></div><div class="rounded-xl bg-slate-50 p-4"><p class="font-bold text-[#10203d]">Payment callback</p><p class="mt-1 break-all text-xs text-slate-500">{{ route('payments.callback') }}</p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><h2 class="text-xl font-black text-[#10203d]">Feature flags</h2><p class="mt-2 text-sm text-slate-500">These flags are the central administrative source for feature availability as modules are connected.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach(['registration_enabled'=>'Public registration','payments_enabled'=>'New payments','renewals_enabled'=>'Automatic renewals','community_enabled'=>'Community','research_enabled'=>'Research hub','live_sessions_enabled'=>'Live sessions'] as $key=>$label)<label class="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key] ?? true)) class="rounded border-slate-300 text-teal-700"><span class="font-bold text-[#10203d]">{{ $label }}</span></label>@endforeach</div><button class="mt-6 rounded-lg bg-teal-700 px-6 py-3 text-sm font-black text-white">Save settings</button></section>
</form>
@endsection
