@extends('layouts.admin')
@section('title',$course->exists?'Build Course':'New Course') @section('heading',$course->exists?'Build '.$course->title:'Create Course')
@section('content')
<form method="POST" action="{{ $course->exists?route('admin.courses.update',$course):route('admin.courses.store') }}" class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">@csrf @if($course->exists)@method('PATCH')@endif
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Course details</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="grid gap-2 sm:col-span-2"><span class="text-xs font-black">Title</span><input name="title" value="{{ old('title',$course->title) }}" class="rounded-lg border-slate-300"></label><label class="grid gap-2"><span class="text-xs font-black">Course key</span><input name="key" value="{{ old('key',$course->key) }}" placeholder="generated_from_title" class="rounded-lg border-slate-300"></label><label class="grid gap-2"><span class="text-xs font-black">Category</span><input name="category" value="{{ old('category',$course->category) }}" class="rounded-lg border-slate-300"></label><label class="grid gap-2 sm:col-span-2"><span class="text-xs font-black">Description</span><textarea name="description" rows="6" class="rounded-lg border-slate-300">{{ old('description',$course->description) }}</textarea></label><label class="grid gap-2"><span class="text-xs font-black">Sort order</span><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$course->sort_order ?? 0) }}" class="rounded-lg border-slate-300"></label><label class="flex items-center gap-3 pt-7"><input type="checkbox" name="is_free" value="1" @checked(old('is_free',$course->is_free)) class="rounded border-slate-300 text-teal-700"><span class="text-sm font-bold">Free access</span></label></div></section>
@include('admin.publishing.status-panel',['item'=>$course,'label'=>'course'])</form>

@if($course->exists)
<section class="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.18em] text-teal-700">Curriculum</p><h2 class="mt-1 text-xl font-black text-[#10203d]">Modules and lessons</h2></div></div><div class="mt-5 space-y-5">@forelse($course->modules as $module)<article class="rounded-xl border border-slate-200 p-4"><form method="POST" action="{{ route('admin.courses.modules.update',[$course,$module]) }}" class="grid gap-3 md:grid-cols-[minmax(0,1fr)_100px_auto]">@csrf @method('PATCH')<div><input name="title" value="{{ $module->title }}" class="w-full rounded-lg border-slate-300 font-bold"><textarea name="description" rows="2" class="mt-2 w-full rounded-lg border-slate-300 text-sm">{{ $module->description }}</textarea></div><input type="number" min="0" name="sort_order" value="{{ $module->sort_order }}" class="h-fit rounded-lg border-slate-300"><button class="h-fit rounded-lg border border-slate-300 px-4 py-3 text-sm font-black">Save</button></form><div class="mt-4 divide-y divide-slate-100 rounded-lg bg-slate-50 px-4">@forelse($module->lessons as $lesson)<div class="flex items-center justify-between gap-4 py-3"><div><p class="font-bold text-[#10203d]">{{ $lesson->title }}</p><p class="text-xs text-slate-500">{{ ucfirst($lesson->status) }} · {{ $lesson->assessments->count() }} assessment(s)</p></div><a href="{{ route('admin.lessons.edit',$lesson) }}" class="text-sm font-black text-teal-700">Edit →</a></div>@empty<p class="py-4 text-sm text-slate-500">No lessons in this module.</p>@endforelse</div><a href="{{ route('admin.modules.lessons.create',$module) }}" class="mt-3 inline-flex text-sm font-black text-teal-700">+ Add lesson</a></article>@empty<p class="text-sm text-slate-500">Add the first module below.</p>@endforelse</div>
<form method="POST" action="{{ route('admin.courses.modules.store',$course) }}" class="mt-6 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-[minmax(0,1fr)_100px_auto]">@csrf<div><input name="title" placeholder="New module title" class="w-full rounded-lg border-slate-300"><textarea name="description" rows="2" placeholder="Description" class="mt-2 w-full rounded-lg border-slate-300 text-sm"></textarea></div><input type="number" min="0" name="sort_order" value="{{ $course->modules->count() }}" class="h-fit rounded-lg border-slate-300"><button class="h-fit rounded-lg bg-[#10203d] px-4 py-3 text-sm font-black text-white">Add module</button></form></section>
@endif
@endsection
