<?php

return [
    'basics' => [
        'id' => 'basics',
        'name' => 'Financial Markets Basics',
        'amount' => 0,
        'currency' => 'USD',
        'external_reference' => 'financial-markets-basics',
        'offer_name' => 'Financial Markets Basics',
        'product_name' => 'Financial Markets Basics',
        'offer_type' => 'course',
        'path' => null,
    ],
    'foundation' => [
        'id' => 'foundation',
        'name' => 'Foundation Path Bundle',
        'amount' => 34900,
        'currency' => 'USD',
        'external_reference' => 'foundation-path',
        'offer_name' => 'Foundation Path',
        'product_name' => 'Foundation',
        'offer_type' => 'bundle',
        'path' => 'Foundation',
    ],
    'trader' => [
        'id' => 'trader',
        'name' => 'Trader Path Bundle',
        'amount' => 89900,
        'currency' => 'USD',
        'external_reference' => 'trader-path',
        'offer_name' => 'Trader Path',
        'product_name' => 'Trader',
        'offer_type' => 'bundle',
        'path' => 'Trader',
    ],
    'investor' => [
        'id' => 'investor',
        'name' => 'Investor Path Bundle',
        'amount' => 109900,
        'currency' => 'USD',
        'external_reference' => 'investor-path',
        'offer_name' => 'Investor Path',
        'product_name' => 'Investor',
        'offer_type' => 'bundle',
        'path' => 'Investor',
    ],
    'ultimate' => [
        'id' => 'ultimate',
        'name' => 'Ultimate Path Bundle',
        'amount' => 149900,
        'currency' => 'USD',
        'external_reference' => 'ultimate-path',
        'offer_name' => 'Ultimate Path',
        'product_name' => 'Ultimate',
        'offer_type' => 'bundle',
        'path' => 'Ultimate',
    ],
    'fixed_income' => [
        'id' => 'fixed_income',
        'name' => 'Fixed Income Analysis & Investments',
        'amount' => 25000,
        'currency' => 'USD',
        'external_reference' => 'fixed-income',
        'offer_name' => 'Fixed Income Analysis & Investments',
        'product_name' => 'Fixed Income Analysis',
        'offer_type' => 'course',
        'path' => null,
    ],
    'equity' => [
        'id' => 'equity',
        'name' => 'Equity Analysis & Investments',
        'amount' => 25000,
        'currency' => 'USD',
        'external_reference' => 'equity-analysis',
        'offer_name' => 'Equity Analysis & Investments',
        'product_name' => 'Equity Analysis & Investments',
        'offer_type' => 'course',
        'path' => null,
    ],
    'derivatives' => [
        'id' => 'derivatives',
        'name' => 'Derivatives 101, Instruments, Valuation, Greeks and Strategies',
        'amount' => 100000,
        'currency' => 'USD',
        'external_reference' => 'derivatives-101',
        'offer_name' => 'Derivatives 101',
        'product_name' => 'Derivatives 101',
        'offer_type' => 'course',
        'path' => null,
    ],
    'lmrss' => [
        'id' => 'lmrss',
        'name' => 'LMRSS Day Trading',
        'amount' => 100000,
        'currency' => 'USD',
        'external_reference' => 'lmrss-day-trading',
        'offer_name' => 'LMRSS Day Trading',
        'product_name' => 'LMRSS Day Trading System',
        'offer_type' => 'course',
        'path' => null,
    ],
];
