@extends('layouts.admin')
@section('title', 'Manage Member')
@section('heading', 'Manage '.$member->first_name.' '.$member->last_name)
@section('content')
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.8fr)]">
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Identity and access</h2><form method="POST" action="{{ route('admin.members.update',$member) }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf @method('PATCH')
@foreach([['first_name','First name'],['last_name','Last name'],['email','Email address'],['timezone','Timezone']] as [$name,$label])<label class="grid gap-2"><span class="text-xs font-black uppercase tracking-wide text-slate-500">{{ $label }}</span><input name="{{ $name }}" value="{{ old($name,$member->$name) }}" class="rounded-lg border-slate-300 text-sm"></label>@endforeach
<label class="grid gap-2"><span class="text-xs font-black uppercase tracking-wide text-slate-500">Role</span><select name="role" class="rounded-lg border-slate-300 text-sm" @disabled(!\App\Support\AdminAccess::allows(auth()->user(),'roles.manage'))>@foreach(\App\Support\AdminAccess::ROLES as $role)<option value="{{ $role }}" @selected(old('role',$member->role)===$role)>{{ ucwords(str_replace('_',' ',$role)) }}</option>@endforeach</select>@if(!\App\Support\AdminAccess::allows(auth()->user(),'roles.manage'))<input type="hidden" name="role" value="{{ $member->role }}">@endif</label>
<label class="grid gap-2"><span class="text-xs font-black uppercase tracking-wide text-slate-500">Account status</span><select name="status" class="rounded-lg border-slate-300 text-sm">@foreach(['Active','Inactive','Suspended'] as $status)<option @selected(old('status',$member->status)===$status)>{{ $status }}</option>@endforeach</select></label>
<label class="grid gap-2"><span class="text-xs font-black uppercase tracking-wide text-slate-500">Current path</span><select name="current_path" class="rounded-lg border-slate-300 text-sm">@foreach(['Free','Foundation','Trader','Investor','Ultimate'] as $path)<option @selected(old('current_path',$member->current_path)===$path)>{{ $path }}</option>@endforeach</select></label>
<label class="flex items-center gap-3 pt-7"><input type="checkbox" name="email_verified" value="1" @checked($member->email_verified_at) class="rounded border-slate-300 text-teal-700"><span class="text-sm font-bold">Email verified</span></label>
<div class="sm:col-span-2"><button class="rounded-lg bg-teal-700 px-5 py-3 text-sm font-black text-white">Save member</button></div></form></section>

<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Grant entitlement</h2><form method="POST" action="{{ route('admin.members.entitlements.store',$member) }}" class="mt-5 grid gap-4">@csrf
<input name="offer_name" placeholder="Offer name" class="rounded-lg border-slate-300 text-sm"><input name="product_name" placeholder="Product name" class="rounded-lg border-slate-300 text-sm"><div class="grid grid-cols-2 gap-3"><input name="offer_type" placeholder="Offer type" class="rounded-lg border-slate-300 text-sm"><input name="external_reference" placeholder="External reference" class="rounded-lg border-slate-300 text-sm"></div><div class="grid grid-cols-3 gap-3"><select name="status" class="rounded-lg border-slate-300 text-sm"><option>Active</option><option>Inactive</option></select><input type="date" name="started_at" class="rounded-lg border-slate-300 text-sm"><input type="date" name="expires_at" class="rounded-lg border-slate-300 text-sm"></div><button class="rounded-lg bg-[#10203d] px-5 py-3 text-sm font-black text-white">Add entitlement</button></form></section>
</div>
<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black text-[#10203d]">Existing entitlements</h2><div class="mt-5 space-y-3">@forelse($member->entitlements as $entitlement)<form method="POST" action="{{ route('admin.members.entitlements.update',[$member,$entitlement]) }}" class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[minmax(220px,1fr)_140px_180px_auto]">@csrf @method('PATCH')<div><p class="font-black text-[#10203d]">{{ $entitlement->offer_name }}</p><p class="text-xs text-slate-500">{{ $entitlement->product_name ?: 'No product name' }}</p></div><select name="status" class="rounded-lg border-slate-300 text-sm"><option @selected($entitlement->status==='Active')>Active</option><option @selected($entitlement->status==='Inactive')>Inactive</option></select><input type="date" name="expires_at" value="{{ $entitlement->expires_at?->format('Y-m-d') }}" class="rounded-lg border-slate-300 text-sm"><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-black">Update</button></form>@empty<p class="text-sm text-slate-500">No entitlement records.</p>@endforelse</div></section>
@endsection
