@extends('layouts.member')
@section('title', 'Research Centre')
@section('content')
<div class="workspace-canvas"><div class="ohc-dashboard-container">
    <x-workspace-heading eyebrow="Market Hub" title="Research Centre" description="Published OHC game plans, reports, recaps, outlooks, and glossary terms in one searchable workspace." />
    <form method="GET" class="research-search"><input type="search" name="q" value="{{ $search }}" placeholder="Search reports, game plans and glossary"><button class="workspace-button">Search</button></form>
    <section class="workspace-section"><div class="workspace-section__heading"><h2>Daily game plans</h2><span>{{ $plans->count() }} results</span></div><div class="research-card-grid">@forelse($plans as $plan)<article class="research-card {{ $hasPremiumPlans ? '' : 'is-gated' }}"><header><span>{{ $plan->market ?: 'Markets' }}</span><time>{{ $plan->trading_date->format('j M Y') }}</time></header><h3>{{ $plan->title }}</h3><p>{{ $hasPremiumPlans ? ($plan->bias ?: 'No bias stated.') : 'Available on Trader and Ultimate Paths.' }}</p>@if($hasPremiumPlans)<ul>@foreach(array_slice($plan->key_levels ?? [],0,3) as $level)<li>{{ $level }}</li>@endforeach</ul><div>@if($plan->pdf_url)<a href="{{ $plan->pdf_url }}" target="_blank" rel="noopener">PDF</a>@endif @if($plan->video_url)<a href="{{ $plan->video_url }}" target="_blank" rel="noopener">Video</a>@endif @if($plan->chart_url)<a href="{{ $plan->chart_url }}" target="_blank" rel="noopener">Charts</a>@endif</div>@else<a href="{{ route('courses.index') }}">View Path options</a>@endif</article>@empty<x-workspace-empty title="No game plans found" copy="Published game plans matching this search will appear here." />@endforelse</div></section>
    <section class="workspace-section"><div class="workspace-section__heading"><h2>Reports and recaps</h2><span>Published by OHC</span></div><div class="report-list">@forelse($reports as $report)<a href="{{ route('research.report',$report) }}"><div><span>{{ $report->category ?: 'Market report' }}</span><h3>{{ $report->title }}</h3><p>{{ Str::limit($report->summary ?: strip_tags($report->body),180) }}</p></div><time>{{ $report->published_at->format('j M Y') }}</time></a>@empty<x-workspace-empty title="No reports found" copy="There are no published reports matching this search." />@endforelse</div>{{ $reports->links() }}</section>
    <section class="workspace-section"><div class="workspace-section__heading"><h2>OHC glossary</h2><span>Structured definitions</span></div><div class="glossary-grid">@forelse($terms as $term)<article><strong>{{ $term->term }}</strong><p>{{ $term->definition }}</p></article>@empty<x-workspace-empty title="No glossary terms found" copy="The Admin content team can publish searchable definitions here. No external definitions are substituted." />@endforelse</div></section>
</div></div>
@endsection
